### ISSUE TITLE
[Question]  how can view the data of channels?

### ISSUE THREAD

**Issue by thiagobspy** [Torsm/ktor-socks#1]
In this piece that we establish the communication between client and server, correct?  

```
  private fun CoroutineScope.relayApplicationData(src: ByteReadChannel, dst: ByteWriteChannel) {
        launch {
            try {
                src.joinTo(dst, false)
            } catch (ignored: Throwable) {
                /*
                * Exceptions while relaying channel traffic (due to closed sockets for example)
                * are not exceptional and are considered the natural end of client/host communication
                */
            }
        }
    }
```

I thought about modifying this piece, to read the data in bytes from the source and write to the destination, so we could keep their communication and we would have access to the data.
Something like that:

```
                while(true){
                    val byte = src.readByte()
                    println(byte)
                    dst.writeByte(byte)
                }
```

But that read one byte at a time (not the whole package at once) and the writing didn't work, the server didn't accept that way.
Do you know how I could solve this problem?

**Comment by torsm** [comment]
That is correct, the `relayApplicationData` function is meant to pass-through all data the client and server are sending to eachother.

You have the right idea, ktor's `joinTo` function (or rather the functions getting called by it) does essentially the same thing, it reads bytes from the source channel and writes them to the destination channel in a loop.

I'm sure the reason your snippet doesn't work as expected is because the destination channel needs to be flushed. Simply adding `dst.flush()` after writing to it will make it work. Just keep in mind that this while loop still has to be within a `launch` block.

This leaves us with the issue that reading and writing individual bytes won't be efficient. The implementation of `joinTo` is a bit more complicated, but generally the following snippet should be a good start:

```kotlin
private fun CoroutineScope.relayApplicationData(src: ByteReadChannel, dst: ByteWriteChannel) {
    launch {
        val buffer = ByteArray(4096)
        try {
            while (true) {
                val bytesRead = src.readAvailable(buffer)
                if (bytesRead == -1) break

                // Do something with the bytes here, like making a string out of them
                println(String(buffer, length = bytesRead))

                dst.writeFully(buffer, 0, bytesRead)
                if (!dst.autoFlush && src.availableForRead == 0) {
                    dst.flush()
                }
            }
        } catch (ignored: Throwable) {
            /*
            * Exceptions while relaying channel traffic (due to closed sockets for example)
            * are not exceptional and are considered the natural end of client/host communication
            */
        }
    }
}
```

**Comment by thiagobspy** [comment]
This worked exactly as I wanted. You helped me a lot, thanks :)
